### ISSUE TITLE
Indexing on every save

### ISSUE THREAD

**Issue by keithmattix** [pat/riddle#101]
I'm running riddle 1.5.12 with thinking-sphinx 3.1.4 on Sphinx 2.2.6, and when I'm running my test suite, every time there's a save on a table that's indexed, the ts:index command seems to be running. Any idea what could be going on?

**Comment by pat** [comment]
Hi Keith,

My first guess is that you've got delta indexing enabled for your Sphinx indices? If you want to disable this for your tests, put `ThinkingSphinx::Deltas.suspend!` in your test setup code.

**Comment by keithmattix** [comment]
Yes, that was it; thank you!
