### ISSUE TITLE
Test files included in the gem file

### ISSUE THREAD

**Issue by jebw** [pat/riddle#94]
Currently theres 11 meg of SQL test files being included within the built Gem - the rest of the gem is tiny in comparison.

The _gem test_ command went away quite some time ago, as did the test_files command still used the Gemspec

Do these still need to be included in the packaged Gem or can they be excluded - would you take a PR to exclude them?

**Comment by pat** [comment]
PR would be great. At some point I'd made sure those files (or at least, the large files within the test suite) weren't being included, but I guess that I broke that somewhere along the line.

**Comment by pat** [comment]
Closing this issue, as @dimko got it sorted in #100.
