### ISSUE TITLE
plugin_dir should be located in common section

### ISSUE THREAD

**Issue by bibendi** [pat/riddle#95]
http://sphinxsearch.com/docs/current.html#conf-plugin-dir

**Comment by pat** [comment]
Just pushed bceb1da39ca489dc2f4aa12518c36deb5a48928b to `develop` that shifts this setting from searchd to common - though it's not backwards compatible at this point. Not quite clear when Sphinx made this change either (somewhere between 2.2.6 and 2.2.10 - but not mentioned in their release notes).

**Comment by bibendi** [comment]
:+1:

**Comment by bibendi** [comment]
@pat, please add another option http://sphinxsearch.com/docs/current.html#conf-query-log-min-msec in searchd section ;)

**Comment by pat** [comment]
Now in `develop` courtesy of 2ce0b7fc54d91ded74b2931c8a295a846e5d60b8.

**Comment by bibendi** [comment]
:+1: x2

**Comment by dentarg** [comment]
Can this be closed now as of https://github.com/pat/riddle/commit/f9364782f992b46b241fa633cc51cad30847c629?

**Comment by pat** [comment]
@dentarg I guess so, yes :)
